# Generated by Django 3.2.5 on 2021-08-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logicentry',
            options={'verbose_name': 'LogicEntry', 'verbose_name_plural': 'LogicEntry'},
        ),
        migrations.AlterModelOptions(
            name='logicstoploss',
            options={'verbose_name': 'LogicStopLoss', 'verbose_name_plural': 'LogicStopLoss'},
        ),
        migrations.AlterModelOptions(
            name='logictakepprofit',
            options={'verbose_name': 'LogicTakepProfit', 'verbose_name_plural': 'LogicTakepProfit'},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'Strategy', 'verbose_name_plural': 'Strategy'},
        ),
        migrations.AlterModelOptions(
            name='timeframe',
            options={'verbose_name': 'TimeFrame', 'verbose_name_plural': 'TimeFrame'},
        ),
    ]
