# Generated by Django 3.2.5 on 2021-08-01 22:47

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20210801_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicentry',
            name='content',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='logicentry',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
