# Generated by Django 3.2.6 on 2021-09-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_remove_coins_coins_taapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolexchange',
            name='exchange',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='symbolexchange',
            name='market',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='symbolexchange',
            name='precision',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
