# Generated by Django 3.2.6 on 2021-08-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_delete_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('coins_taapi', models.CharField(max_length=20)),
                ('coins_exchange', models.CharField(max_length=20)),
                ('to_import', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Coins',
                'verbose_name_plural': 'Coins',
            },
        ),
    ]
