# Generated by Django 3.2.6 on 2021-09-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_auto_20210902_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolexchange',
            name='quantity_precision',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
