# Generated by Django 3.2.5 on 2021-08-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_auto_20210801_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='long',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='short',
            field=models.BooleanField(default=False),
        ),
    ]
