# Generated by Django 3.2.6 on 2021-08-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coins',
            name='to_import',
        ),
        migrations.AlterField(
            model_name='coins',
            name='coins_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symbolexchange'),
        ),
        migrations.AlterField(
            model_name='coins',
            name='coins_taapi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symboltaapiapi'),
        ),
    ]
