# Generated by Django 3.2.5 on 2021-08-02 14:53

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_auto_20210802_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logicentry',
            old_name='content',
            new_name='function',
        ),
        migrations.AddField(
            model_name='logicstoploss',
            name='function',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AddField(
            model_name='logictakepprofit',
            name='function',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
