# Generated by Django 3.2.6 on 2021-08-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_auto_20210803_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logicexit',
            old_name='stop_loss',
            new_name='stop_loss_long',
        ),
        migrations.RenameField(
            model_name='logicexit',
            old_name='take_profit',
            new_name='stop_loss_short',
        ),
        migrations.RemoveField(
            model_name='logicexit',
            name='long',
        ),
        migrations.RemoveField(
            model_name='logicexit',
            name='short',
        ),
        migrations.AddField(
            model_name='logicexit',
            name='take_profit_long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='logicexit',
            name='take_profit_short',
            field=models.FloatField(default=0),
        ),
    ]
