# Generated by Django 3.2.6 on 2021-09-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_symbolexchange_quantity_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolexchange',
            name='precision',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='symbolexchange',
            name='quantity_precision',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
