# Generated by Django 3.2.5 on 2021-08-02 14:54

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_auto_20210802_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('function', django_quill.fields.QuillField(blank=True)),
            ],
            options={
                'verbose_name': 'LogicExit',
                'verbose_name_plural': 'LogicExit',
            },
        ),
    ]
