# Generated by Django 3.2.6 on 2021-08-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_auto_20210804_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logicentry',
            name='long',
        ),
        migrations.RemoveField(
            model_name='logicentry',
            name='short',
        ),
    ]
