# Generated by Django 3.2.5 on 2021-08-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_logicexit'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='logic_exit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='strategy.logicexit'),
            preserve_default=False,
        ),
    ]
