# Generated by Django 3.2.6 on 2021-09-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_delete_coins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SymbolTaapiApi',
        ),
    ]
