# Generated by Django 3.2.5 on 2021-08-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_strategy_logic_exit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='logic_stoploss',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='logic_takeprofit',
        ),
        migrations.DeleteModel(
            name='LogicStopLoss',
        ),
        migrations.DeleteModel(
            name='LogicTakepProfit',
        ),
    ]
