# Generated by Django 3.2.6 on 2021-08-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_auto_20210805_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolexchange',
            name='to_import',
        ),
        migrations.RemoveField(
            model_name='timeframe',
            name='to_import',
        ),
    ]
