# Generated by Django 3.2.6 on 2021-09-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_delete_symboltaapiapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolexchange',
            name='market',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
