# Generated by Django 3.2.5 on 2021-08-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0008_auto_20210802_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='long',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='short',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='sleep_profitloss',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='sleep_run',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='take_profit',
        ),
        migrations.AddField(
            model_name='logicentry',
            name='ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='logicentry',
            name='sleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logicexit',
            name='sleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logicexit',
            name='stop_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='logicexit',
            name='take_profit',
            field=models.FloatField(default=0),
        ),
    ]
