# Generated by Django 3.2.6 on 2021-08-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_auto_20210809_0149'),
        ('strategy', '0008_auto_20210807_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogicEntry',
        ),
        migrations.DeleteModel(
            name='LogicExit',
        ),
    ]
