# Generated by Django 3.2.5 on 2021-08-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0009_auto_20210802_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='logic_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.logicentry'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='logic_exit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.logicexit'),
        ),
    ]
