# Generated by Django 3.2.5 on 2021-08-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0010_auto_20210802_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicentry',
            name='long',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logicentry',
            name='short',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logicexit',
            name='long',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logicexit',
            name='short',
            field=models.BooleanField(default=False),
        ),
    ]
