# Generated by Django 3.2.5 on 2021-08-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0011_auto_20210802_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='logic_entry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='strategy.logicentry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategy',
            name='logic_exit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='strategy.logicexit'),
            preserve_default=False,
        ),
    ]
