# Generated by Django 3.2.6 on 2021-08-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0013_auto_20210802_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='live_mode',
            field=models.BooleanField(default=False),
        ),
    ]
