# Generated by Django 3.2.6 on 2021-08-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0014_strategy_live_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logicexit',
            name='sleep',
        ),
    ]
