version: '3.9'

services:
  tas_dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 manage.py runserver 0:8000 --verbosity 3
    container_name: tas_developmet
    volumes:
      - .:/tas
    ports:
      - 8000:8000
    env_file:
      - .env.dev

  postgres_db:
    container_name: tas_db
    image: kartoza/postgis:13.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    depends_on:
      - tas_dev

#  vuejs:
#    build:
#      context: .
#      dockerfile: ./DockerfileFrontEnd
#    depends_on:
#      - tas_dev
#    ports:
#      - 9091:9091

volumes:
  postgres_data:
