version: '3.9'

services:

  tas_dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    #command: daphne -b 0.0.0.0 -p 8000 tas.asgi:application
    command: python3 manage.py runserver 0:8000 --verbosity 3
    container_name: tas_developmet
    volumes:
      - .:/tas
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - postgres_db

  postgres_db:
    container_name: tas_db
    image: postgres:13.3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

  redis:
    container_name: tas_redis
    image: redis:6.2.5
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    expose:
      - 6379
#  vuejs:
#    build:
#      context: .
#      dockerfile: ./DockerfileFrontEnd
#    depends_on:
#      - tas_dev
#    ports:
#      - "9091:9091"

volumes:
  postgres_data:
  redis-data:
