# Generated by Django 3.2.5 on 2021-07-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ByBt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('time', models.IntegerField(blank=True, default=0)),
                ('symbol', models.CharField(max_length=100)),
                ('longRateList', models.JSONField(blank=True, null=True)),
                ('shortsRateList', models.JSONField(blank=True, null=True)),
                ('priceList', models.JSONField(blank=True, null=True)),
                ('longShortRateList', models.JSONField(blank=True, null=True)),
                ('longShortRateListLast', models.FloatField(blank=True, default=0)),
                ('dateList', models.JSONField(blank=True, null=True)),
                ('timeType', models.JSONField(blank=True, null=True)),
                ('avg', models.FloatField(blank=True, default=0)),
                ('sum', models.FloatField(blank=True, default=0)),
                ('candle', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('tf', models.CharField(max_length=15)),
                ('unix', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('indicators', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
