# Generated by Django 3.2.6 on 2021-08-09 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByBt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('time', models.IntegerField(blank=True, default=0)),
                ('symbol', models.CharField(max_length=100)),
                ('longRateList', models.JSONField(blank=True, null=True)),
                ('shortsRateList', models.JSONField(blank=True, null=True)),
                ('priceList', models.JSONField(blank=True, null=True)),
                ('longShortRateList', models.JSONField(blank=True, null=True)),
                ('longShortRateListLast', models.FloatField(blank=True, default=0)),
                ('dateList', models.JSONField(blank=True, null=True)),
                ('timeType', models.JSONField(blank=True, null=True)),
                ('avg', models.FloatField(blank=True, default=0)),
                ('sum', models.FloatField(blank=True, default=0)),
                ('candle', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('symbol', models.CharField(max_length=15)),
                ('tf', models.CharField(max_length=15)),
                ('unix', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('indicators', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Importer',
                'verbose_name_plural': 'Importer',
            },
        ),
        migrations.CreateModel(
            name='TrendChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('long', models.FloatField(default=0)),
                ('short', models.FloatField(default=0)),
                ('trade_long', models.BooleanField(default=False)),
                ('trade_short', models.BooleanField(default=False)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symbolexchange')),
                ('time_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.timeframe')),
            ],
            options={
                'verbose_name': 'TrendChecker',
                'verbose_name_plural': 'TrendChecker',
            },
        ),
        migrations.CreateModel(
            name='ToImportCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symbolexchange')),
                ('time_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.timeframe')),
            ],
            options={
                'verbose_name': 'ToImportCoins',
                'verbose_name_plural': 'ToImportCoins',
            },
        ),
    ]
