# Generated by Django 3.2.6 on 2021-08-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendchecker',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symbolexchange'),
        ),
        migrations.AddField(
            model_name='trendchecker',
            name='time_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.timeframe'),
        ),
    ]
