# Generated by Django 3.2.4 on 2021-06-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bybt',
            name='longShortRateListLast',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
