# Generated by Django 3.2.5 on 2021-08-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importer',
            options={'verbose_name': 'Importer', 'verbose_name_plural': 'Importer'},
        ),
    ]
