# Generated by Django 3.2.5 on 2021-08-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_importer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('tf', models.CharField(max_length=15)),
                ('long', models.FloatField(default=0)),
                ('short', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TrendChecker',
                'verbose_name_plural': 'TrendChecker',
            },
        ),
    ]
