# Generated by Django 3.2.5 on 2021-08-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_trendchecker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendchecker',
            name='trade_long',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trendchecker',
            name='trade_short',
            field=models.BooleanField(default=False),
        ),
    ]
