# Generated by Django 3.2.4 on 2021-07-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_bybt_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('symbol', models.CharField(max_length=15)),
                ('tf', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('ema', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
