# Generated by Django 3.2.4 on 2021-07-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_exchangerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exchangerecord',
            name='flgEnable',
        ),
        migrations.RemoveField(
            model_name='exchangerecord',
            name='updated_at',
        ),
    ]
