# Generated by Django 3.2.5 on 2021-08-01 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
        ('analytics', '0004_auto_20210801_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendchecker',
            name='tf',
        ),
        migrations.AddField(
            model_name='trendchecker',
            name='time_frame',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='strategy.timeframe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trendchecker',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symbolexchange'),
        ),
    ]
