# Generated by Django 3.2.4 on 2021-07-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20210722_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerecord',
            name='unix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
