# Generated by Django 3.2.5 on 2021-08-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20210801_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendchecker',
            name='short',
            field=models.FloatField(default=0),
        ),
    ]
