# Generated by Django 3.2.5 on 2021-08-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_trendchecker_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendchecker',
            name='avg',
            field=models.FloatField(default=0),
        ),
    ]
