# Generated by Django 3.2.5 on 2021-07-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_exchangerecord_unix'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerecord',
            name='atr',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='bollinger',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='fibonacciretracement',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='macd',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='pivotpoints',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='rsi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='stochrsi',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
