# Generated by Django 3.2.5 on 2021-07-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20210723_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerecord',
            old_name='bollinger',
            new_name='bbands',
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='breakaway',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='cci',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='doji',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='hammer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='ma',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='stoch',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='trix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerecord',
            name='volatility',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
