# Generated by Django 3.2.5 on 2021-07-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20210723_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerecord',
            name='ema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
