# Generated by Django 3.2.5 on 2021-08-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_remove_trendchecker_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='importer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='importer',
            name='flgEnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='importer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
