# Generated by Django 3.2.5 on 2021-07-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_exchangerecord_ema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('tf', models.CharField(max_length=15)),
                ('unix', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeRecord',
        ),
    ]
