# Generated by Django 3.2.5 on 2021-08-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20210801_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendchecker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trendchecker',
            name='flgEnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trendchecker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
