# Generated by Django 3.2.5 on 2021-07-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_auto_20210728_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='importer',
            name='indicators',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
