# Generated by Django 3.2.6 on 2021-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_bot_user'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot',
            field=models.ManyToManyField(null=True, to='bot.Bot'),
        ),
    ]
