# Generated by Django 3.2.5 on 2021-08-01 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20210801_0312'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0004_alter_bot_binance_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BinanceAccount',
        ),
        migrations.AddField(
            model_name='exchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
