# Generated by Django 3.2.5 on 2021-08-01 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20210801_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ExchangeList',
                'verbose_name_plural': 'ExchangeList',
            },
        ),
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchangelist'),
        ),
    ]
