# Generated by Django 3.2.5 on 2021-08-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20210801_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='name',
            new_name='exchange',
        ),
    ]
