# Generated by Django 3.2.6 on 2021-08-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_user_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bot',
        ),
    ]
