# Generated by Django 3.2.6 on 2021-08-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_remove_user_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
