# Generated by Django 3.2.6 on 2021-08-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_exchange_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
