# Generated by Django 3.2.6 on 2021-08-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_user_telegram_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counter_bot',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
