# Generated by Django 3.2.6 on 2021-08-05 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_user_counter_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exchange',
        ),
        migrations.AddField(
            model_name='exchange',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
