# Generated by Django 3.2.6 on 2021-08-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_auto_20210805_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exchange',
        ),
    ]
