# Generated by Django 3.2.6 on 2021-08-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_delete_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='counter_bot',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
