# Generated by Django 3.2.5 on 2021-07-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtest', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('STOP', 'STOP'), ('START', 'START')], default='STOP', max_length=50)),
                ('quantity_investment', models.FloatField(default=0)),
                ('leverage', models.IntegerField(default=0)),
                ('live', models.BooleanField(default=False)),
                ('execution', models.BooleanField(default=False)),
                ('binance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.binanceaccount')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BotLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('entry_candle', models.FloatField(blank=True, default=0)),
                ('stop_loss', models.BooleanField(blank=True, default=False)),
                ('take_profit', models.BooleanField(blank=True, default=False)),
                ('candle_stop_loss', models.FloatField(blank=True, default=0)),
                ('candle_take_profit', models.FloatField(blank=True, default=0)),
                ('entry_candle_date', models.DateTimeField(blank=True, null=True)),
                ('candle_stop_loss_date', models.DateTimeField(blank=True, null=True)),
                ('candle_take_profit_date', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.bot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
