# Generated by Django 3.2.5 on 2021-07-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('symbol_taapi', models.CharField(max_length=15)),
                ('symbol_exchange', models.CharField(max_length=10)),
                ('time_frame', models.CharField(max_length=10)),
                ('ratio', models.IntegerField(blank=True, default=0)),
                ('take_profit', models.FloatField(default=0)),
                ('stop_loss', models.FloatField(default=0)),
                ('sleep_run', models.IntegerField(blank=True, default=0)),
                ('sleep_profitloss', models.IntegerField(blank=True, default=0)),
                ('indicators', models.JSONField(blank=True, null=True)),
                ('ema_interval', models.JSONField(blank=True, null=True)),
                ('quantity_investement', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
