# Generated by Django 3.2.6 on 2021-08-09 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0001_initial'),
        ('bot', '0001_initial'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexchange',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchangelist'),
        ),
        migrations.AddField(
            model_name='userexchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategybot',
            name='logic_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.logicentry'),
        ),
        migrations.AddField(
            model_name='strategybot',
            name='logic_exit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.logicexit'),
        ),
        migrations.AddField(
            model_name='strategybot',
            name='time_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.timeframe'),
        ),
        migrations.AddField(
            model_name='bufferstreamwebsocket',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.symbolexchange'),
        ),
        migrations.AddField(
            model_name='bufferrecorddata',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.symbolexchange'),
        ),
        migrations.AddField(
            model_name='botlogger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bot',
            name='coins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.coins'),
        ),
        migrations.AddField(
            model_name='bot',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.strategybot'),
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
