# Generated by Django 3.2.5 on 2021-07-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='logic_entry_function',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='logic_stoploss_function',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='logic_takeprofit_function',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
