# Generated by Django 3.2.5 on 2021-07-28 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('indicator', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymbolExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('symbol', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymbolTaapiApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('symbol', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('time_frame', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bot',
            name='ema_interval',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='time_frame',
        ),
        migrations.AddField(
            model_name='bot',
            name='leverage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('DISABLED', 'DISABLED'), ('RUNNING', 'RUNNING')], default='DISABLED', max_length=50),
        ),
        migrations.RemoveField(
            model_name='bot',
            name='indicators',
        ),
        migrations.AlterField(
            model_name='bot',
            name='quantity_investement',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('ratio', models.FloatField(default=0)),
                ('take_profit', models.FloatField(default=0)),
                ('stop_loss', models.FloatField(default=0)),
                ('logic_entry_function', models.CharField(max_length=200)),
                ('logic_takeprofit_function', models.CharField(max_length=200)),
                ('logic_stoploss_function', models.CharField(max_length=200)),
                ('time_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.timeframe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('api_key', models.CharField(max_length=200)),
                ('api_secret', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bot',
            name='binance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.binanceaccount'),
        ),
        migrations.AddField(
            model_name='bot',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.strategy'),
        ),
        migrations.AddField(
            model_name='bot',
            name='indicators',
            field=models.ManyToManyField(to='bot.Indicator'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='symbol_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.symbolexchange'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='symbol_taapi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.symboltaapiapi'),
        ),
    ]
