# Generated by Django 3.2.5 on 2021-07-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='indicators',
        ),
    ]
