# Generated by Django 3.2.6 on 2021-08-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bufferrecorddata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bufferrecorddata',
            name='volume',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
