# Generated by Django 3.2.6 on 2021-08-03 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('live_mode', models.BooleanField(default=False)),
                ('logic_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.logicentry')),
                ('logic_exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.logicexit')),
                ('symbol_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symbolexchange')),
                ('symbol_taapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symboltaapiapi')),
                ('time_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.timeframe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StrategyBot',
                'verbose_name_plural': 'StrategyBot',
            },
        ),
        migrations.AlterField(
            model_name='bot',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.strategybot'),
        ),
    ]
