# Generated by Django 3.2.5 on 2021-07-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210728_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='ratio',
            field=models.FloatField(default=0),
        ),
    ]
