# Generated by Django 3.2.5 on 2021-07-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_bot_strategy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Bot', 'verbose_name_plural': 'Bot'},
        ),
        migrations.AlterModelOptions(
            name='botlogger',
            options={'verbose_name': 'BotLogger', 'verbose_name_plural': 'BotLogger'},
        ),
        migrations.AlterField(
            model_name='botlogger',
            name='bot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
            preserve_default=False,
        ),
    ]
