# Generated by Django 3.2.5 on 2021-07-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_bot_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('indicator', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bot',
            name='ema_interval',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='indicators',
        ),
        migrations.AddField(
            model_name='bot',
            name='indicators',
            field=models.ManyToManyField(to='bot.Indicator'),
        ),
    ]
