# Generated by Django 3.2.5 on 2021-08-01 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20210801_0312'),
        ('bot', '0003_auto_20210730_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='binance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.exchange'),
        ),
    ]
