# Generated by Django 3.2.6 on 2021-08-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210803_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategybot',
            options={'verbose_name': 'Strategy', 'verbose_name_plural': 'Strategy'},
        ),
    ]
