# Generated by Django 3.2.5 on 2021-07-29 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_quantity_investement_bot_quantity_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('entry_candle', models.FloatField(blank=True, default=0)),
                ('stop_loss', models.BooleanField(blank=True, default=False)),
                ('take_profit', models.BooleanField(blank=True, default=False)),
                ('candle_stop_loss', models.FloatField(blank=True, default=0)),
                ('candle_take_profit', models.FloatField(blank=True, default=0)),
                ('entry_candle_date', models.DateTimeField(blank=True, null=True)),
                ('candle_stop_loss_date', models.DateTimeField(blank=True, null=True)),
                ('candle_take_profit_date', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.bot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
