# Generated by Django 3.2.6 on 2021-08-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_bufferrecorddata_unix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bufferrecorddata',
            name='unix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
