# Generated by Django 3.2.5 on 2021-07-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botlogger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indicator',
        ),
    ]
