# Generated by Django 3.2.5 on 2021-07-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210728_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('DISABLE', 'DISABLE'), ('ENABLE', 'ENABLE'), ('RUNNING', 'RUNNING')], default='DISABLE', max_length=50),
        ),
    ]
