# Generated by Django 3.2.6 on 2021-08-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_strategybot_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='user',
        ),
    ]
