# Generated by Django 3.2.5 on 2021-07-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_delete_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolexchange',
            name='to_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeframe',
            name='to_import',
            field=models.BooleanField(default=False),
        ),
    ]
