# Generated by Django 3.2.5 on 2021-08-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_binance_account_bot_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='long',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='short',
            field=models.BooleanField(default=False),
        ),
    ]
