# Generated by Django 3.2.6 on 2021-08-03 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0005_remove_bot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategybot',
            name='user',
        ),
        migrations.AddField(
            model_name='strategybot',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
