# Generated by Django 3.2.5 on 2021-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_bot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='quantity_investement',
            field=models.FloatField(default=0),
        ),
    ]
