# Generated by Django 3.2.5 on 2021-07-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20210729_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('DISABLED', 'DISABLED'), ('ENABLED', 'ENABLED'), ('RUNNING', 'RUNNING')], default='DISABLED', max_length=50),
        ),
    ]
