# Generated by Django 3.2.5 on 2021-07-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_bot_quantity_investement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
