# Generated by Django 3.2.6 on 2021-08-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_delete_bufferstreamwebsocket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bufferrecorddata',
            name='symbol',
            field=models.CharField(db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bufferrecorddata',
            name='time_frame',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='bufferrecorddata',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
