# Generated by Django 3.2.6 on 2021-08-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_delete_strategy'),
        ('bot', '0006_auto_20210803_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategybot',
            name='symbol_exchange',
        ),
        migrations.AddField(
            model_name='strategybot',
            name='symbol_exchange',
            field=models.ManyToManyField(blank=True, null=True, to='strategy.SymbolExchange'),
        ),
        migrations.RemoveField(
            model_name='strategybot',
            name='symbol_taapi',
        ),
        migrations.AddField(
            model_name='strategybot',
            name='symbol_taapi',
            field=models.ManyToManyField(blank=True, null=True, to='strategy.SymbolTaapiApi'),
        ),
    ]
