# Generated by Django 3.2.6 on 2021-08-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20210819_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BufferRecordData',
        ),
    ]
