# Generated by Django 3.2.5 on 2021-08-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_bot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='status',
        ),
    ]
