# Generated by Django 3.2.5 on 2021-07-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_bot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='execution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('STOP', 'STOP'), ('START', 'START')], default='STOP', max_length=50),
        ),
    ]
