# Generated by Django 3.2.5 on 2021-08-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_bot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='long',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='short',
        ),
    ]
