# Generated by Django 3.2.6 on 2021-08-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_delete_bufferrecorddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferRecordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('time_frame', models.CharField(db_index=True, max_length=4)),
                ('open_candle', models.FloatField(blank=True, default=0)),
                ('close_candle', models.FloatField(blank=True, default=0)),
                ('high_candle', models.FloatField(blank=True, default=0)),
                ('low_candle', models.FloatField(blank=True, default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unix', models.CharField(blank=True, max_length=100, null=True)),
                ('volume', models.FloatField(blank=True)),
            ],
        ),
    ]
