# Generated by Django 3.2.6 on 2021-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_coins'),
        ('bot', '0008_bot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategybot',
            name='symbol_exchange',
        ),
        migrations.RemoveField(
            model_name='strategybot',
            name='symbol_taapi',
        ),
        migrations.AddField(
            model_name='strategybot',
            name='coins',
            field=models.ManyToManyField(blank=True, null=True, to='strategy.Coins'),
        ),
    ]
