# Generated by Django 3.2.5 on 2021-07-29 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20210729_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='sleep_profitloss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bot',
            name='sleep_run',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bot',
            name='strategy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.strategy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='symbol_exchange',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.symbolexchange'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='symbol_taapi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.symboltaapiapi'),
            preserve_default=False,
        ),
    ]
