# Generated by Django 3.2.5 on 2021-07-29 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20210729_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='sleep_profitloss',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='sleep_run',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='symbol_exchange',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='symbol_taapi',
        ),
        migrations.AddField(
            model_name='strategy',
            name='sleep_profitloss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sleep_run',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='symbol_exchange',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.symbolexchange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='symbol_taapi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.symboltaapiapi'),
            preserve_default=False,
        ),
    ]
