# Generated by Django 3.2.5 on 2021-08-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20210802_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='leverage',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='live',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='quantity_investment',
        ),
    ]
