# Generated by Django 3.2.6 on 2021-08-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_bufferrecorddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bufferrecorddata',
            name='key',
            field=models.CharField(db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
    ]
