# Generated by Django 3.2.6 on 2021-08-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_auto_20210803_2017'),
        ('bot', '0009_auto_20210803_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='coins',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='strategy.coins'),
            preserve_default=False,
        ),
    ]
