# Generated by Django 3.2.5 on 2021-07-28 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20210728_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyDispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('logic_entry_function', models.CharField(max_length=200)),
                ('logic_takeprofit_function', models.CharField(max_length=200)),
                ('logic_stoploss_function', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bot',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.strategydispatcher'),
        ),
    ]
