# Generated by Django 3.2.5 on 2021-07-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20210729_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='symbol_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.symbolexchange'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='symbol_taapi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.symboltaapiapi'),
        ),
    ]
