# Generated by Django 3.2.6 on 2021-08-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_bufferrecorddata_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bufferrecorddata',
            name='key',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
