# Generated by Django 3.2.5 on 2021-07-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20210728_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='logic_entry_function',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='logic_stoploss_function',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='logic_takeprofit_function',
        ),
    ]
