# Generated by Django 3.2.6 on 2021-08-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_bot_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategybot',
            name='live_mode',
        ),
    ]
