# Generated by Django 3.2.5 on 2021-07-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20210729_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='symbol_exchange',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.symbolexchange'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategy',
            name='symbol_taapi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.symboltaapiapi'),
            preserve_default=False,
        ),
    ]
