# Generated by Django 3.2.6 on 2021-08-05 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0010_delete_exchange'),
        ('bot', '0011_remove_strategybot_live_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('api_key', models.CharField(max_length=200)),
                ('api_secret', models.CharField(max_length=200)),
                ('balance_futures', models.FloatField(blank=True, default=0)),
                ('balance_spot', models.FloatField(blank=True, default=0)),
                ('leverage', models.IntegerField(blank=True, default=0)),
                ('live', models.BooleanField(default=False)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchangelist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserExchange',
                'verbose_name_plural': 'UserExchange',
            },
        ),
    ]
