# Generated by Django 3.2.5 on 2021-07-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20210728_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('DISABLED', 'DISABLED'), ('RUNNING', 'RUNNING')], default='DISABLED', max_length=50),
        ),
    ]
