# Generated by Django 3.2.5 on 2021-07-28 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_bot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('time_frame', models.CharField(max_length=10)),
                ('ratio', models.FloatField(default=0)),
                ('take_profit', models.FloatField(default=0)),
                ('stop_loss', models.FloatField(default=0)),
                ('logic_entry_function', models.CharField(max_length=200)),
                ('logic_takeprofit_function', models.CharField(max_length=200)),
                ('logic_stoploss_function', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bot',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='time_frame',
        ),
        migrations.AlterField(
            model_name='bot',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.strategy'),
        ),
        migrations.DeleteModel(
            name='StrategyDispatcher',
        ),
    ]
