# Generated by Django 3.2.5 on 2021-07-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_strategy_symbolexchange_symboltaapiapi_timeframe'),
        ('bot', '0012_auto_20210729_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.strategy'),
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
        migrations.DeleteModel(
            name='SymbolExchange',
        ),
        migrations.DeleteModel(
            name='SymbolTaapiApi',
        ),
        migrations.DeleteModel(
            name='TimeFrame',
        ),
    ]
