# Generated by Django 3.2.6 on 2021-08-29 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0001_initial'),
        ('bot', '0013_auto_20210820_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('running', models.BooleanField(default=False)),
                ('abort', models.BooleanField(default=False)),
                ('market_spot', models.BooleanField(default=False)),
                ('market_futures', models.BooleanField(default=False)),
                ('leverage', models.IntegerField(default=1)),
                ('amount', models.FloatField(default=11)),
                ('live', models.BooleanField(default=False)),
                ('coins', models.ManyToManyField(to='strategy.Coins')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.strategybot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bot',
            },
        ),
    ]
