# Generated by Django 3.2.6 on 2021-08-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_bufferstreamwebsocket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bufferstreamwebsocket',
            name='time_frame',
            field=models.CharField(max_length=4),
        ),
    ]
