# Generated by Django 3.2.5 on 2021-07-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        ('bot', '0013_auto_20210729_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='binance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.binanceaccount'),
        ),
        migrations.DeleteModel(
            name='BinanceAccount',
        ),
    ]
