# Generated by Django 3.2.6 on 2021-08-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_clusterbot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusterbot',
            options={'verbose_name': 'ClusterBot', 'verbose_name_plural': 'ClusterBot'},
        ),
    ]
