# Generated by Django 3.2.6 on 2021-08-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_bufferstreamwebsocket_time_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlogger',
            name='stop_loss_ratio',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='botlogger',
            name='take_profit_ratio',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
