# Generated by Django 3.2.6 on 2021-08-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_clusterbot_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterbot',
            name='coins',
        ),
        migrations.AlterField(
            model_name='clusterbot',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
