# Generated by Django 3.2.6 on 2021-08-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20210805_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlogger',
            name='thread',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
