# Generated by Django 3.2.6 on 2021-08-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_botlogger_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='perpetual',
            field=models.BooleanField(default=False),
        ),
    ]
