# Generated by Django 3.2.6 on 2021-09-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20210830_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('key', models.CharField(db_index=True, max_length=20)),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('time_frame', models.CharField(db_index=True, max_length=4)),
                ('data', models.JSONField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
