# Generated by Django 3.2.5 on 2021-07-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20210728_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='time_frame',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.timeframe'),
            preserve_default=False,
        ),
    ]
