# Generated by Django 3.2.6 on 2021-08-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_bot_perpetual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategybot',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='strategybot',
            name='user',
        ),
    ]
