# Generated by Django 3.2.6 on 2021-09-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_computeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlogger',
            name='profit',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
