# Generated by Django 3.2.6 on 2021-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_botlogger_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterbot',
            name='profit',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
