# Generated by Django 3.2.6 on 2021-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_bot_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='stopped',
            field=models.BooleanField(default=False),
        ),
    ]
