# Generated by Django 3.2.6 on 2021-08-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_bot_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='abort',
            field=models.BooleanField(default=False),
        ),
    ]
