# Generated by Django 3.2.6 on 2021-09-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_alter_bot_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeddata',
            name='key',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
