# Generated by Django 3.2.6 on 2021-09-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_alter_computeddata_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeddata',
            name='symbol',
            field=models.CharField(db_index=True, max_length=25),
        ),
    ]
