# Generated by Django 3.2.6 on 2021-08-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_bot_abort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='stopped',
        ),
        migrations.AddField(
            model_name='strategybot',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
