# Generated by Django 3.2.6 on 2021-08-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_auto_20210807_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='perpetual',
        ),
    ]
