# Generated by Django 3.2.6 on 2021-08-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_remove_botlogger_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlogger',
            name='long',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='botlogger',
            name='short',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
