# Generated by Django 3.2.6 on 2021-08-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_auto_20210807_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='market_futures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='market_spot',
            field=models.BooleanField(default=False),
        ),
    ]
