# Generated by Django 3.2.6 on 2021-08-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_auto_20210807_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='leverage',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
