# Generated by Django 3.2.6 on 2021-08-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_bot_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='amount',
            field=models.FloatField(blank=True, default=10),
        ),
    ]
