# Generated by Django 3.2.6 on 2021-08-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_bot_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategybot',
            name='market_futures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategybot',
            name='market_spot',
            field=models.BooleanField(default=False),
        ),
    ]
