# Generated by Django 3.2.6 on 2021-08-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_auto_20210808_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexchange',
            name='leverage',
        ),
    ]
