# Generated by Django 3.2.6 on 2021-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_remove_userexchange_leverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botlogger',
            name='thread',
        ),
        migrations.AlterField(
            model_name='bot',
            name='amount',
            field=models.FloatField(default=11),
        ),
        migrations.AlterField(
            model_name='bot',
            name='leverage',
            field=models.FloatField(default=1),
        ),
    ]
