# Generated by Django 3.2.6 on 2021-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_auto_20210808_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='leverage',
            field=models.IntegerField(default=1),
        ),
    ]
