# Generated by Django 3.2.6 on 2021-08-08 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0035_alter_bot_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchange',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exchange.user'),
            preserve_default=False,
        ),
    ]
