# Generated by Django 3.2.6 on 2021-08-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_bufferrecorddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexchange',
            name='live',
        ),
        migrations.AddField(
            model_name='bot',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
