# Generated by Django 3.2.6 on 2021-08-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_auto_20210809_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategybot',
            name='market_futures',
        ),
        migrations.RemoveField(
            model_name='strategybot',
            name='market_spot',
        ),
    ]
