# Generated by Django 3.2.6 on 2021-08-09 23:17

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_strategy', models.CharField(max_length=200)),
                ('start_period', models.DateField()),
                ('end_period', models.DateField()),
                ('running', models.BooleanField(default=False)),
                ('scheduled', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('initial_investment', models.FloatField(default=1000)),
            ],
            options={
                'verbose_name': 'BackTesting',
                'verbose_name_plural': 'BackTesting',
            },
        ),
        migrations.CreateModel(
            name='LogicEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('ratio', models.FloatField(default=0)),
                ('function', django_quill.fields.QuillField(blank=True)),
            ],
            options={
                'verbose_name': 'LogicEntry',
                'verbose_name_plural': 'LogicEntry',
            },
        ),
        migrations.CreateModel(
            name='LogicExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('takeprofit', models.FloatField(default=0)),
                ('stoploss', models.FloatField(default=0)),
                ('function', django_quill.fields.QuillField(blank=True)),
            ],
            options={
                'verbose_name': 'LogicExit',
                'verbose_name_plural': 'LogicExit',
            },
        ),
        migrations.CreateModel(
            name='StatisticsPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('entry', models.IntegerField(blank=True, default=0)),
                ('time_frame', models.CharField(blank=True, max_length=10)),
                ('take_profit', models.IntegerField(blank=True, default=0)),
                ('stop_loss', models.IntegerField(blank=True, default=0)),
                ('profit_ratio', models.IntegerField(blank=True, default=0)),
                ('loss_ratio', models.IntegerField(blank=True, default=0)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('logic_entry', models.CharField(blank=True, max_length=250)),
                ('logic_exit', models.CharField(blank=True, max_length=250)),
                ('profit_loss_percentage', models.FloatField(blank=True, default=0)),
                ('initial_investment', models.FloatField(blank=True, default=0)),
                ('current_wallet', models.FloatField(blank=True, default=0)),
                ('composite_value', models.FloatField(blank=True, default=0)),
                ('start_period', models.DateField(blank=True, null=True)),
                ('end_period', models.DateField(blank=True, null=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.backtest')),
            ],
            options={
                'verbose_name': 'StatisticsPortfolio',
                'verbose_name_plural': 'StatisticsPortfolio',
            },
        ),
        migrations.CreateModel(
            name='BackTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_frame', models.CharField(blank=True, max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('entry_candle', models.FloatField(blank=True, default=0)),
                ('stop_loss', models.BooleanField(blank=True, default=False)),
                ('take_profit', models.BooleanField(blank=True, default=False)),
                ('candle_stop_loss', models.FloatField(blank=True, default=0)),
                ('candle_take_profit', models.FloatField(blank=True, default=0)),
                ('entry_candle_date', models.DateTimeField(blank=True, null=True)),
                ('candle_stop_loss_date', models.DateTimeField(blank=True, null=True)),
                ('candle_take_profit_date', models.DateTimeField(blank=True, null=True)),
                ('profit_loss', models.FloatField(blank=True, default=0)),
                ('loss_percentage', models.FloatField(blank=True, default=0)),
                ('profit_percentage', models.FloatField(blank=True, default=0)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.backtest')),
            ],
            options={
                'verbose_name': 'BacktestLog',
                'verbose_name_plural': 'BacktestLog',
            },
        ),
        migrations.AddField(
            model_name='backtest',
            name='logic_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.logicentry'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='logic_exit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.logicexit'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symbolexchange'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='time_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.timeframe'),
        ),
    ]
