# Generated by Django 3.2.5 on 2021-07-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(blank=True, max_length=100)),
                ('time_frame', models.CharField(blank=True, max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('entry_candle', models.FloatField(blank=True, default=0)),
                ('stop_loss', models.BooleanField(blank=True, default=False)),
                ('take_profit', models.BooleanField(blank=True, default=False)),
                ('candle_stop_loss', models.FloatField(blank=True, default=0)),
                ('candle_take_profit', models.FloatField(blank=True, default=0)),
                ('entry_candle_date', models.DateTimeField(blank=True, null=True)),
                ('candle_stop_loss_date', models.DateTimeField(blank=True, null=True)),
                ('candle_take_profit_date', models.DateTimeField(blank=True, null=True)),
                ('profit_loss', models.FloatField(blank=True, default=0)),
                ('function_name_logic_entry', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('algorithm', models.CharField(blank=True, max_length=100)),
                ('entry', models.IntegerField(blank=True, default=0)),
                ('time_frame', models.CharField(blank=True, max_length=10)),
                ('take_profit', models.IntegerField(blank=True, default=0)),
                ('stop_loss', models.IntegerField(blank=True, default=0)),
                ('profit_ratio', models.IntegerField(blank=True, default=0)),
                ('loss_ratio', models.IntegerField(blank=True, default=0)),
                ('profit_loss_percentage', models.FloatField(blank=True, default=0)),
                ('function_name_take_profit', models.CharField(blank=True, max_length=100)),
                ('function_name_stop_loss', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
