# Generated by Django 3.2.5 on 2021-07-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='algorithm',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
