# Generated by Django 3.2.5 on 2021-07-30 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_auto_20210729_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(blank=True, max_length=100)),
                ('time_frame', models.CharField(blank=True, max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('entry_candle', models.FloatField(blank=True, default=0)),
                ('stop_loss', models.BooleanField(blank=True, default=False)),
                ('take_profit', models.BooleanField(blank=True, default=False)),
                ('candle_stop_loss', models.FloatField(blank=True, default=0)),
                ('candle_take_profit', models.FloatField(blank=True, default=0)),
                ('entry_candle_date', models.DateTimeField(blank=True, null=True)),
                ('candle_stop_loss_date', models.DateTimeField(blank=True, null=True)),
                ('candle_take_profit_date', models.DateTimeField(blank=True, null=True)),
                ('profit_loss', models.FloatField(blank=True, default=0)),
                ('function_name_logic_entry', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='candle_stop_loss',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='candle_stop_loss_date',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='candle_take_profit',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='candle_take_profit_date',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='entry_candle',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='entry_candle_date',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='function_name_logic_entry',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='time_frame',
        ),
        migrations.AddField(
            model_name='backtest',
            name='end_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='start_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backtest.strategy'),
            preserve_default=False,
        ),
    ]
