# Generated by Django 3.2.6 on 2021-08-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_backtest_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
