# Generated by Django 3.2.5 on 2021-07-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_alter_backtest_algorithm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackTest',
        ),
    ]
