# Generated by Django 3.2.6 on 2021-08-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_auto_20210803_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategybacktesting',
            options={'verbose_name': 'StrategyBacktesting', 'verbose_name_plural': 'StrategyBacktesting'},
        ),
    ]
