# Generated by Django 3.2.5 on 2021-07-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtest', '0003_delete_backtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(blank=True, max_length=100)),
                ('entry_candle', models.FloatField(blank=True, default=0)),
                ('entry_candle_date', models.DateTimeField(blank=True, null=True)),
                ('counter_stop_loss', models.IntegerField(blank=True, default=0)),
                ('counter_take_profit', models.IntegerField(blank=True, default=0)),
                ('percentage_win', models.IntegerField(blank=True, default=0)),
                ('percentage_loss', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
