# Generated by Django 3.2.5 on 2021-07-30 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
        ('bot', '0002_alter_bot_strategy'),
        ('backtest', '0003_auto_20210730_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='logic_entry',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='logic_stoploss',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='logic_takeprofit',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='symbol_exchange',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='symbol_taapi',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='time_frame',
        ),
        migrations.AlterField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy'),
        ),
        migrations.DeleteModel(
            name='LogicEntry',
        ),
        migrations.DeleteModel(
            name='LogicStopLoss',
        ),
        migrations.DeleteModel(
            name='LogicTakepProfit',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
        migrations.DeleteModel(
            name='SymbolExchange',
        ),
        migrations.DeleteModel(
            name='SymbolTaapiApi',
        ),
        migrations.DeleteModel(
            name='TimeFrame',
        ),
    ]
