# Generated by Django 3.2.6 on 2021-08-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0004_alter_strategybacktesting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategybacktesting',
            options={'verbose_name': 'Strategy', 'verbose_name_plural': 'Strategy'},
        ),
    ]
