# Generated by Django 3.2.6 on 2021-08-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0004_remove_backtest_name_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestlog',
            name='long',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='backtestlog',
            name='short',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
