# Generated by Django 3.2.6 on 2021-08-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0005_auto_20210810_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtestlog',
            name='long',
        ),
        migrations.RemoveField(
            model_name='backtestlog',
            name='short',
        ),
        migrations.AddField(
            model_name='backtest',
            name='long',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='backtest',
            name='short',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
