# Generated by Django 3.2.5 on 2021-07-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0005_auto_20210724_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtest',
            name='counter_take_profit',
        ),
        migrations.AlterField(
            model_name='backtest',
            name='counter_stop_loss',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
