# Generated by Django 3.2.5 on 2021-07-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0005_backtest_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
