# Generated by Django 3.2.6 on 2021-08-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0006_toimportcoins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToImportCoins',
        ),
    ]
