# Generated by Django 3.2.5 on 2021-07-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0006_auto_20210724_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtest',
            name='counter_stop_loss',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='percentage_loss',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='percentage_win',
        ),
        migrations.AddField(
            model_name='backtest',
            name='stop_loss',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='backtest',
            name='take_profit',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
