# Generated by Django 3.2.5 on 2021-07-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0006_backtest_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticsportfolio',
            name='algorithm',
        ),
        migrations.AddField(
            model_name='backtest',
            name='initial_investment',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
