# Generated by Django 3.2.5 on 2021-07-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0007_auto_20210730_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtestlog',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='backtestlog',
            name='function_name_logic_entry',
        ),
        migrations.RemoveField(
            model_name='statisticsportfolio',
            name='function_name_stop_loss',
        ),
        migrations.RemoveField(
            model_name='statisticsportfolio',
            name='function_name_take_profit',
        ),
        migrations.AddField(
            model_name='backtestlog',
            name='backtest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backtest.backtest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statisticsportfolio',
            name='backtest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backtest.backtest'),
            preserve_default=False,
        ),
    ]
