# Generated by Django 3.2.6 on 2021-08-09 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0008_auto_20210809_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategybacktesting',
            name='logic_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtest.logicentry'),
        ),
        migrations.AlterField(
            model_name='strategybacktesting',
            name='logic_exit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtest.logicexit'),
        ),
    ]
