# Generated by Django 3.2.5 on 2021-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0008_auto_20210730_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsportfolio',
            name='composite_value',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='statisticsportfolio',
            name='net_profit',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
