# Generated by Django 3.2.5 on 2021-07-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0008_auto_20210725_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='profit_loss',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
