# Generated by Django 3.2.5 on 2021-07-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0009_auto_20210730_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsportfolio',
            name='initial_investment',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
