# Generated by Django 3.2.5 on 2021-07-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0010_backtest_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('flgEnable', models.BooleanField(default=True)),
                ('algorithm', models.CharField(blank=True, max_length=100)),
                ('entry', models.IntegerField(blank=True, default=0)),
                ('take_profit', models.IntegerField(blank=True, default=0)),
                ('stop_loss', models.IntegerField(blank=True, default=0)),
                ('profit_ratio', models.IntegerField(blank=True, default=0)),
                ('loss_ratio', models.IntegerField(blank=True, default=0)),
                ('profit_loss_percentage', models.FloatField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
