# Generated by Django 3.2.6 on 2021-08-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0010_auto_20210809_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logicentry',
            options={'verbose_name': 'LogicEntry', 'verbose_name_plural': 'LogicEntry'},
        ),
        migrations.AlterModelOptions(
            name='logicexit',
            options={'verbose_name': 'LogicExit', 'verbose_name_plural': 'LogicExit'},
        ),
    ]
