# Generated by Django 3.2.5 on 2021-07-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0011_auto_20210730_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticsportfolio',
            old_name='net_profit',
            new_name='current_wallet',
        ),
    ]
