# Generated by Django 3.2.5 on 2021-07-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0011_statisticsportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='time_frame',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='statisticsportfolio',
            name='time_frame',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
