# Generated by Django 3.2.6 on 2021-08-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0012_remove_logicentry_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
