# Generated by Django 3.2.5 on 2021-07-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0012_auto_20210727_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='function_name_logic_entry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='statisticsportfolio',
            name='function_name_stop_loss',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='statisticsportfolio',
            name='function_name_take_profit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
