# Generated by Django 3.2.6 on 2021-08-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0013_backtest_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='initial_investment',
            field=models.FloatField(default=1000),
        ),
    ]
