# Generated by Django 3.2.5 on 2021-08-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0013_auto_20210801_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backtest',
            options={'verbose_name': 'BackTesting', 'verbose_name_plural': 'BackTesting'},
        ),
    ]
