# Generated by Django 3.2.6 on 2021-08-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0014_alter_backtest_initial_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
