# Generated by Django 3.2.6 on 2021-08-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0015_backtest_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
