# Generated by Django 3.2.6 on 2021-08-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0009_auto_20210809_0149'),
        ('backtest', '0017_auto_20210809_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='end_period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='logic_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.logicentry'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='logic_exit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.logicexit'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='start_period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symbolexchange'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='time_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.timeframe'),
        ),
    ]
