# Generated by Django 3.2.6 on 2021-08-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0020_alter_backtest_name_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsportfolio',
            name='end_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticsportfolio',
            name='start_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
