# Generated by Django 3.2.6 on 2021-08-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0021_auto_20210809_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsportfolio',
            name='logic_entry',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='statisticsportfolio',
            name='logic_exit',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='statisticsportfolio',
            name='symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
